---
title: "Thesis_Modeling"
output:
  html_document: default
  word_document: default
---
```{r}
library(ggplot2)
library(lme4)
library(ggeffects)
library(stargazer)
library(lm.beta)
library(segmented)
```


```{r setup, include=FALSE}
#Overall data sheet, including all field locations and vegetation types

Gosliner_Data <- read.csv("https://github.com/sgosliner/masters_thesis/raw/main/Gosliner_ThesisData.csv")

#Creating density variables for goldenrod and mugwort. Cages are 0.25 m^2 so stem density = (count / 0.25)
Gosliner_Data$Goldenrod_Density <- Gosliner_Data$Goldenrod_StemCount / 0.25
Gosliner_Data$Mugwort_Density <- Gosliner_Data$Mugwort_StemCount / 0.25

Gosliner_Data$Forb_Density <- Gosliner_Data$Goldenrod_Density + Gosliner_Data$Mugwort_Density

head(Gosliner_Data)
```



```{r cars}
#ONLY GOLDENROD DATA
Goldenrod <- Gosliner_Data[Gosliner_Data$Plant %in% c("Goldenrod"), ]
#creating new dataframe from overall data to only include goldenrod

head(Goldenrod)

hist(Goldenrod$Biomass)
#histogram of untransformed mass is right skewed

hist(log(Goldenrod$Biomass))
#log transformed mass is more normally distributed

Goldenrod$logBiomass <- log(Goldenrod$Biomass + 1)
#log transforming biomass to achieve normality

Goldenrod$Trophic <- as.factor(Goldenrod$Trophic_Treatment)
#relabeling Trophic_Treatment variable as factor

Goldenrod$InvStatus <- as.factor(Goldenrod$Invasive)
#relabeling Invasive variable as factor

lm.Goldenrod2 <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Temp_MeanMax + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Goldenrod)
#GLM predicting biomass from trophic treatment, invasive treatment, standardized grasshopper survival, average daily mean temperature, standardized mean stem height, and standardized steam density
#relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only goldenrod used as reference

summary(lm.Goldenrod2)

lm.beta(lm.Goldenrod2)
#appending of GLM to include beta coefficients

summary(lm.beta(lm.Goldenrod2))

stargazer(lm.beta(lm.Goldenrod2), type = "text",
          digits = 3,
          star.cutoffs = c(0.05, 0.01, 0.001),
          digit.separator = "")
```

```{r}
#Site specific goldenrod models
#For site specific linear models, temperature components dropped because they are consistent within-sites

#Wallingford goldenrod model
Goldenrod.Wallingford <- Goldenrod[Goldenrod$Location %in% c("Wallingford"), ]
#Creating dataframe with only Wallingford goldenrod data

lm.Goldenrod.Wallingford <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Goldenrod.Wallingford)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only goldenrod used as reference

summary(lm.beta(lm.Goldenrod.Wallingford))

#WaterProp goldenrod model
Goldenrod.WaterProp <- Goldenrod[Goldenrod$Location %in% c("WaterProp"), ]
#Creating dataframe with only WaterProp goldenrod data

lm.Goldenrod.WaterProp <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Goldenrod.WaterProp)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only goldenrod used as reference

summary(lm.beta(lm.Goldenrod.WaterProp))

#Flanders goldenrod model
Goldenrod.Flanders <- Goldenrod[Goldenrod$Location %in% c("Flanders"), ]
#Creating dataframe with only Flanders goldenrod data

lm.Goldenrod.Flanders <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Goldenrod.Flanders)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only goldenrod used as reference

summary(lm.beta(lm.Goldenrod.Flanders))
```


```{r pressure, echo=FALSE}
#MUGWORT ONLY DATA
Mugwort <- Gosliner_Data[Gosliner_Data$Plant %in% c("Mugwort"), ]
#creating new dataframe from overall data to only include mugwort

hist(Mugwort$Biomass)
#histogram of untransformed mass is right skewed

hist(log(Mugwort$Biomass))
#log transformed mass is more normally distributed

Mugwort$logBiomass <- log(Mugwort$Biomass + 1)
#log transforming biomass to achieve normality

Mugwort$Trophic <- as.factor(Mugwort$Trophic_Treatment)
#relabeling Trophic_Treatment variable as factor

Mugwort$InvStatus <- as.factor(Mugwort$Invasive)
#relabeling Invasive variable as factor

lm.Mugwort2 <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Invasive") + Grasshopper_Avg + Temp_MeanMax + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Mugwort)
#GLM predicting biomass from trophic treatment, invasive treatment, standardized grasshopper survival, average daily mean temperature, standardized mean stem height, and standardized steam density
#relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "invasive" aka only mugwort used as reference

summary(lm.beta(lm.Mugwort2))
```

```{r}
#Site specific Mugwort models
#For site specific linear models, temperature components dropped because they are consistent within-sites

#Wallingford Mugwort model
Mugwort.Wallingford <- Mugwort[Mugwort$Location %in% c("Wallingford"), ]
#Creating dataframe with only Wallingford Mugwort data

lm.Mugwort.Wallingford <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Invasive") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Mugwort.Wallingford)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "invasive" aka only Mugwort used as reference

summary(lm.beta(lm.Mugwort.Wallingford))

#WaterProp Mugwort model
Mugwort.WaterProp <- Mugwort[Mugwort$Location %in% c("WaterProp"), ]
#Creating dataframe with only WaterProp Mugwort data

lm.Mugwort.WaterProp <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Invasive") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Mugwort.WaterProp)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "invasive" aka only Mugwort used as reference

summary(lm.beta(lm.Mugwort.WaterProp))

#Flanders Mugwort model
Mugwort.Flanders <- Mugwort[Mugwort$Location %in% c("Flanders"), ]
#Creating dataframe with only Flanders Mugwort data

lm.Mugwort.Flanders <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Invasive") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Mugwort.Flanders)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "invasive" aka only Mugwort used as reference

summary(lm.beta(lm.Mugwort.Flanders))
```



```{r}
#Grass Data Only
Grass <- Gosliner_Data[Gosliner_Data$Plant %in% c("Grass"), ]
#creating new dataframe from overall data to only include grass

hist(Grass$Biomass)
#histogram of untransformed mass is right skewed

hist(log(Grass$Biomass))
#log transformed mass is more normally distributed

Grass$logBiomass <- log(Grass$Biomass + 1)
#log transforming biomass to achieve normality

Grass$Trophic <- as.factor(Grass$Trophic_Treatment)
#relabeling Trophic_Treatment variable as factor

Grass$InvStatus <- as.factor(Grass$Invasive)
#relabeling Invasive variable as factor

lm.Grass2 <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Temp_MeanMax + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Grass)
#GLM predicting biomass from trophic treatment, invasive treatment, standardized grasshopper survival, average daily mean temperature, standardized mean stem height, and standardized steam density
#relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only goldenrod used as reference

summary(lm.beta(lm.Grass2))
```

```{r}
#Site specific Grass models
#For site specific linear models, temperature components dropped because they are consistent within-sites

#Wallingford Grass model
Grass.Wallingford <- Grass[Grass$Location %in% c("Wallingford"), ]
#Creating dataframe with only Wallingford Grass data

lm.Grass.Wallingford <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Grass.Wallingford)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only goldenrod used as reference

summary(lm.beta(lm.Grass.Wallingford))

#WaterProp Grass model
Grass.WaterProp <- Grass[Grass$Location %in% c("WaterProp"), ]
#Creating dataframe with only WaterProp Grass data

lm.Grass.WaterProp <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Grass.WaterProp)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only golderod used as reference

summary(lm.beta(lm.Grass.WaterProp))

#Flanders Grass model
Grass.Flanders <- Grass[Grass$Location %in% c("Flanders"), ]
#Creating dataframe with only Flanders Grass data

lm.Grass.Flanders <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Grass.Flanders)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only goldenrod used as reference

summary(lm.beta(lm.Grass.Flanders))
```


```{r}
#Other Data Only
Other <- Gosliner_Data[Gosliner_Data$Plant %in% c("Other"), ]
#creating new dataframe from overall data to only include other

hist(Other$Biomass)
#histogram of untransformed mass is right skewed

hist(log(Other$Biomass))
#log transformed mass is more normally distributed

Other$logBiomass <- log(Other$Biomass + 1)
#log transforming biomass to achieve normality

Other$Trophic <- as.factor(Other$Trophic_Treatment)
#relabeling Trophic_Treatment variable as factor

Other$InvStatus <- as.factor(Other$Invasive)
#relabeling Invasive variable as factor

lm.Other2 <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Temp_MeanMax + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Other)
#GLM predicting biomass from trophic treatment, invasive treatment, standardized grasshopper survival, average daily mean temperature, standardized mean stem height, and standardized steam density
#relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only goldenrod used as reference

summary(lm.beta(lm.Other2))
```

```{r}
#Site specific Other models
#For site specific linear models, temperature components dropped because they are consistent within-sites

#Wallingford Other model
Other.Wallingford <- Other[Other$Location %in% c("Wallingford"), ]
#Creating dataframe with only Wallingford Other data

lm.Other.Wallingford <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Other.Wallingford)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only Other used as reference

summary(lm.beta(lm.Other.Wallingford))

#WaterProp Other model
Other.WaterProp <- Other[Other$Location %in% c("WaterProp"), ]
#Creating dataframe with only WaterProp Other data

lm.Other.WaterProp <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Other.WaterProp)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only Other used as reference

summary(lm.beta(lm.Other.WaterProp))

#Flanders Other model
Other.Flanders <- Other[Other$Location %in% c("Flanders"), ]
#Creating dataframe with only Flanders Other data

lm.Other.Flanders <- lm(logBiomass ~ relevel(Trophic, ref = "Plant") + relevel(InvStatus, ref = "Native") + Grasshopper_Avg + Goldenrod_Density + Goldenrod_StemHeight + Mugwort_Density + Mugwort_StemHeight, data = Other.Flanders)
#creating lm from duplicate dataset. relevel() function used to set reference levels for categorical variables
#For Trophic variable, "plant" aka one trophic level used as reference
#For InvStatus variable, "native" aka only Other used as reference

summary(lm.beta(lm.Other.Flanders))
```

```{r}
#Biomass vs. mugwort and goldenrod stem count data and plots.

Grass$col <- (as.integer(as.factor(Grass$Invasive))+1)
#creating color for grass data based on invasive categorization of plot

boxplot(logBiomass ~ Invasive, data = Grass)
#visualizing grass biomass by invasive status of plot
stripchart(logBiomass ~ Invasive, data = Grass,              # Data
           method = "jitter", # Random noise
           pch = 19,          # Pch symbols
           col = 4,           # Color of the symbol
           vertical = TRUE,   # Vertical mode
           add = TRUE)        # Add it over
#overlaying datapoints on top of boxplot

Grass.Invasive <- Grass[Grass$Invasive %in% c("Invasive", "Mixed"), ]
#creating dataframe that contains grass data from only invasive and mixed plots

fit.mug <- lm(logBiomass ~ Mugwort_Density, data=Grass.Invasive)
#fit simple linear regression model


segmented.fit.mug <- segmented(fit.mug, seg.Z = ~Mugwort_Density, psi=52)
#fit piecewise regression model to original model, estimating a breakpoint at x=52

summary(segmented.fit.mug)
#view summary of segmented model

davies.test(fit.mug)
#davies test that tests for a significant change in slope



Grass.Native <- Grass[Grass$Invasive %in% c("Native", "Mixed"), ]
#creating color for grass data based on invasive categorization of plot

#fit simple linear regression model
fit.gold <- lm(logBiomass ~ Goldenrod_Density, data=Grass.Native)

#fit piecewise regression model to original model, estimating a breakpoint at x=52
segmented.fit.gold <- segmented(fit.gold, seg.Z = ~Goldenrod_Density, psi=52)

#view summary of segmented model
summary(segmented.fit.gold)

davies.test(fit.gold)
#davies test that tests for a significant change in slope

#plotting grass biomass vs mugwort density with segmented trendline added
plot(jitter(Grass$Mugwort_Density, factor = 1), jitter(Grass$logBiomass, factor = 1), pch=16, ## filled in circles,
  col=(as.integer(as.factor(Grass$Invasive))+1), xlim = c(0, 120), ylab = "log(Grass Biomass)", xlab = "Mugwort Stem Density",
  main = "Mugwort"
)
legend('topright', legend = levels(as.factor(Grass$Invasive)), col = 2:4, cex = 1, pch = 16)
plot(segmented.fit.mug, add=T)

#plotting grass biomass vs goldenrod density with segmented trendline added
plot(jitter(Grass$Goldenrod_Density, factor = 1), jitter(Grass$logBiomass, factor = 1), pch=16, ## filled in circles,
  col=(as.integer(as.factor(Grass$Invasive))+1), xlim = c(0, 120), ylab = "log(Grass Biomass)", xlab = "Goldenrod Stem Density",
  main = "Goldenrod"
)
legend('topright', legend = levels(as.factor(Grass$Invasive)), col = 2:4, cex = 1, pch = 16)
plot(segmented.fit.gold, add=T)
```


```{r}
lm.Inv.Forb <- lm(logBiomass ~ Forb_Density, data=Grass[Grass$Invasive %in% c("Invasive"), ])
#creating linear model for grass biomass by forb density using only invasive data

lm.Nat.Forb <- lm(logBiomass ~ Forb_Density, data=Grass[Grass$Invasive %in% c("Native"), ])
#creating linear model for grass biomass by forb density using only native data

lm.Mixed.Forb <- lm(logBiomass ~ Forb_Density, data=Grass[Grass$Invasive %in% c("Mixed"), ])
#creating linear model for grass biomass by forb density using only mixed data


summary(lm.beta(lm.Mixed.Forb))
summary(lm.beta(lm.Nat.Forb))
summary(lm.beta(lm.Inv.Forb))

#plotting grass biomass vs dominant forb density. Adding trendlines for individual linear models above for native, invasive, and mixed data
plot(jitter(Grass$Forb_Density, factor = 0), jitter(Grass$logBiomass, factor = 0), pch=16, ## filled in circles,
  col=(as.integer(as.factor(Grass$Invasive))+1), xlim = c(0, 120), ylab = "log(Grass Biomass)", xlab = expression("Dominant Forb Density (stems / m"^"2"*")"),
  main = "Effect of Dominant Forbs on Grass"
)
legend('topright', legend = levels(as.factor(Grass$Invasive)), col = 2:4, cex = 1, pch = 16)
clip(8, 116, 0, 100)
abline(lm.Nat.Forb, col = 4, lwd = 2)
clip(24, 104, 0, 100)
abline(lm.Inv.Forb, col = 2, lwd = 2)
clip(24, 96, 0, 100)
abline(lm.Mixed.Forb, col = 3, lwd = 2)


fit.forb <- lm(logBiomass ~ Forb_Density, data=Grass)
summary(fit.forb)
#linear model for overall effect of dominant forb density on grass
```


```{r}
#Mugwort vs. goldenrod stem density by location

MixedPlots <- Gosliner_Data[Gosliner_Data$Invasive %in% c("Mixed"), ]
#Creating dataframe with only mixed plot data

lm.Flanders.Stem <- lm(Goldenrod_Density ~ Mugwort_Density, data = MixedPlots[MixedPlots$Location %in% c("Flanders"), ])
#creating linear model for goldenrod stem count by mugwort stem count using only flanders data

lm.Wallingford.Stem <- lm(Goldenrod_Density ~ Mugwort_Density, data = MixedPlots[MixedPlots$Location %in% c("Wallingford"), ])
#creating linear model for goldenrod stem count by mugwort stem count using only wallingford data

lm.WaterProp.Stem <- lm(Goldenrod_Density ~ Mugwort_Density, data = MixedPlots[MixedPlots$Location %in% c("WaterProp"), ])
#creating linear model for goldenrod stem count by mugwort stem count using only waterprop data

plot(MixedPlots$Mugwort_Density, MixedPlots$Goldenrod_Density, pch=16, ## filled in circles,
  col=(as.integer(as.factor(MixedPlots$Location))+1), xlim = c(0, 70), ylab = expression("S. rugosa Density (stems / m"^"2"*")"), xlab = expression("A. vulgaris Density (stems / m"^"2"*")")
  )
legend('topright', legend = c("Flanders","Wallingford", "Branford"), col = 2:4, cex = 1, pch = 16)
#plotting goldenrod stem count by mugwort stem count, points colored by location
clip(4, 48, 0, 100)
abline(lm.Flanders.Stem, col = 2, lwd = 2)
#adding flander regression line clipped to data limits
clip(16, 64, 0, 100)
abline(lm.Wallingford.Stem, col = 3, lwd = 2)
#adding wallingford regression line clipped to data limits
clip(12, 64, 0, 100)
abline(lm.WaterProp.Stem, col = 4, lwd = 2)
#adding waterprop regression line clipped to data limits


summary(lm.beta(lm.Flanders.Stem))
summary(lm.beta(lm.Wallingford.Stem))
summary(lm.beta(lm.WaterProp.Stem))
```


















